import "./globals.css";
import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Outfit } from "next/font/google";

const nextFont = Outfit({ subsets: ["latin"] });

import "@mantine/core/styles.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={nextFont.className}>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
